# Generated by Django 5.0 on 2025-07-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('transport', '0002_transport_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('transport', 'seat_number')},
        ),
    ]
