# Generated by Django 5.0 on 2025-07-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='total_seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
