# Generated by Django 5.2.4 on 2025-07-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transport_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus')], default='flight', max_length=10),
            preserve_default=False,
        ),
    ]
